//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCrawl
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecorderInfo
    {
        public int Id { get; set; }
        public string CurrentState { get; set; }
        public string Concluse { get; set; }
        public string RecorderUser { get; set; }
        public string PaiChaUser { get; set; }
        public string Year { get; set; }
        public string Area { get; set; }
        public string Viliage { get; set; }
        public string Adress { get; set; }
        public string HzUserName { get; set; }
        public string HzPhone { get; set; }
        public string IsProll { get; set; }
        public string Catelog { get; set; }
        public string EarthNature { get; set; }
        public string BuildYear { get; set; }
        public string BuildArea { get; set; }
        public string BasicNature { get; set; }
        public string OverFlow { get; set; }
        public string Desgin { get; set; }
        public string ReDesgin { get; set; }
        public string IsHaveScript { get; set; }
        public string ReDesignCotent { get; set; }
        public string NowUsage { get; set; }
        public string Structure { get; set; }
        public string DataSource { get; set; }
        public string AuditTime { get; set; }
        public string TechUserName { get; set; }
        public string TechUserPhone { get; set; }
        public string TechUserUnit { get; set; }
    }
}
